language: python

matrix:
  include:
    - name: "Python 2.7 on Linux"
      python: 2.7
      dist: trusty
      before_install:
        - python -m pip install --upgrade pip
    - name: "Python 3.7 on Linux"
      python: 3.7
      dist: xenial
      before_install:
        - python -m pip install --upgrade pip
    - name: "Python 2.7 on macOS"
      os: osx
      osx_image: xcode9.4
      language: shell
      before_install:
        - python -m pip install --upgrade pip
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_cache:
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          - "$HOME/Library/Caches/pip"
      addons:
        homebrew:
          # update: true
          packages: python3
      before_install:
        - python3 -m pip install --upgrade virtualenv
        - virtualenv -p python3 --system-site-packages "$HOME/venv"
        - source "$HOME/venv/bin/activate"
    - name: "Python 2.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python2 vcredist2008
        - choco install --ignore-dependencies vcpython27
        - python -m pip install --upgrade pip
      env: PATH=/c/Python27:/c/Python27/Scripts:$PATH
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - source travis/build_wheel.sh
script:
  - ls *.whl
  - echo "done."
